services:
    python:
        image: python:3.8
        restart: unless-stopped
        init: true
        volumes:
            - ..:/workspace:cached
        ports: 
            - 3020:6006
            - 3021:8500
            - 3022:8501
        command: sleep infinity
    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        volumes:
            - ../vis:/app
        ports:  
            - 3023:3000
        links: 
            - "fastapi:api"
    fastapi:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
        restart: unless-stopped
        environment: 
            VARIABLE_NAME: api
            WORKERS_PER_CORE: 0.5
            MAX_WORKERS: 24
        volumes:
            - ../api/code:/app
        ports:  
            - 3024:80
        links: 
            - "database:db"
        entrypoint: /start-reload.sh
        command: /bin/sh -c "pip3 install --user -r requirements.txt"
    database:
        image: mysql:5.7
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ../db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports: 
            - 3025:80
        links: 
            - "database:db"
        depends_on:
            - database
    tensorflow:
        image: jupyter/tensorflow-notebook
        restart: unless-stopped
        ports: 
            - 3026:8888
            - 3027:6006
        volumes:
            - ../code:/home/jovyan/work
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            GRANT_SUDO: "yes"
            RESTARTABLE: "yes"
        entrypoint: start-notebook.sh --NotebookApp.password='' --NotebookApp.token=''
    